[signal]
#listen ip port
host = "0.0.0.0"
port = "8443"

[redis]
addrs = [":6379"]
password = ""
db = 0

[etcd]
# ["ip:port", "ip:port"]
addrs = ["127.0.0.1:2379"]

[log]
level = "info"
# level = "debug"